asv-soft/asv-drones

src/Asv.Drones.Gui.Map/Core/Internals/Core.cs
src/Asv.Drones.Gui.Map/MapView.axaml.cs

---
- https://app.asana.com/0/0/1204103964800990

Fixed app crash after doing max zoom and min zoom

---

.github/workflows/macos_release.yml
.github/workflows/ubuntu_release.yml
.github/workflows/windows_release.yml

---
- https://app.asana.com/0/0/1204099460291748

Added workflow for each OS

---

src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/DefaultUavRttItemProvider.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/HomeDistance/HomeDistanceUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/HomeDistance/HomeDistanceUavRttView.axaml.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/HomeDistance/HomeDistanceUavRttViewModel.cs

---
- https://app.asana.com/0/0/1204172142501390
- https://app.asana.com/0/0/1204172142501386

Added home distance uav rtt

---

src/Asv.Drones.Gui.Core/Services/Localization/ReadOnlyMeasures/RelativeTime.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/DefaultUavRttItemProvider.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/FlightTime/FlightTimeUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/FlightTime/FlightTimeUavRttView.axaml.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/FlightTime/FlightTimeUavRttViewModel.cs

---
- https://app.asana.com/0/0/1204172142501390

Added flight time uav rtt

---

src/Asv.Drones.Gui.Uav/RS.Designer.cs
src/Asv.Drones.Gui.Uav/RS.resx
src/Asv.Drones.Gui.Uav/RS.ru.resx
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/Battery/BatteryUavRttViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/FlightTime/FlightTimeUavRttViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/Gps/GpsUavRttViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/HomeDistance/HomeDistanceUavRttViewModel.cs

---
- https://app.asana.com/0/0/1204190916572692

Added N\A value for RTT items

---

src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/CpuLoad/CpuLoadUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/CpuLoad/CpuLoadUavRttView.axaml.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/CpuLoad/CpuLoadUavRttViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/DefaultUavRttItemProvider.cs

---
- https://app.asana.com/0/0/1204268189581298

Implemented cpu load rtt item

---

src/Asv.Drones.Gui.Core/App.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/Current/CurrentUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/DefaultUavRttItemProvider.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/LinkQuality/LinkQualityUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/LinkQuality/LinkQualityUavRttView.axaml.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/LinkQuality/LinkQualityUavRttViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/Voltage/VoltageUavRttItemView.axaml

---
- https://app.asana.com/0/0/1204268189581292

Added link quality rtt item

---

src/Asv.Drones.Gui.Core/Controls/ConnectionQuality.axaml.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/CpuLoad/CpuLoadUavRttView.axaml

---
- https://app.asana.com/0/0/1204278863191749

Fixed disappearance of battery indicator

---

src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/DefaultGbsRttItemProvider.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/Observation/ObservationGbsRttView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/VisibleSatellites/VisibleSatellitesGbsRttView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/VisibleSatellites/VisibleSatellitesGbsRttView.axaml.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/VisibleSatellites/VisibleSatellitesGbsRttViewModel.cs

---
- https://app.asana.com/0/0/1204337701409837

Added visible satellites gbs rtt item

---

src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/Accuracy/AccuracyGbsRttViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/BaseStationMode/BaseStationModeGbsRttView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/BaseStationMode/BaseStationModeGbsRttView.axaml.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/BaseStationMode/BaseStationModeGbsRttViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/DefaultGbsRttItemProvider.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavView.axaml

---
- https://app.asana.com/0/0/1204268189581120

Added base station mode rtt gbs item

---

src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/FlightMissionWidgetProvider.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Dialogs/AutoModeViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Dialogs/FixedModeViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsViewModel.cs

---
- https://app.asana.com/0/0/1204337701409809
- https://app.asana.com/0/0/1204337701409815

Save and restore for auto and fixed mode params implemented

---

src/Asv.Drones.Gui.Gbs/RS.Designer.cs
src/Asv.Drones.Gui.Gbs/RS.resx
src/Asv.Drones.Gui.Gbs/RS.ru.resx
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/Accuracy/AccuracyGbsRttView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/BaseStationMode/BaseStationModeGbsRttView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/DGpsRate/DGpsRateGbsRttView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/LinkQuality/LinkQualityGbsRttView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/Observation/ObservationGbsRttView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/VisibleSatellites/VisibleSatellitesGbsRttView.axaml
src/Asv.Drones.Gui.Uav/RS.Designer.cs
src/Asv.Drones.Gui.Uav/RS.resx
src/Asv.Drones.Gui.Uav/RS.ru.resx
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/Battery/BatteryUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/CpuLoad/CpuLoadUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/Current/CurrentUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/FlightTime/FlightTimeUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/HomeDistance/HomeDistanceUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/LinkQuality/LinkQualityUavRttView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/Voltage/VoltageUavRttItemView.axaml

---
- https://app.asana.com/0/0/1204337701409861

Added language localization for all rtt items

---

src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Dialogs/AutoModeView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Dialogs/FixedModeView.axaml

Markup changed to stop UI from jumping around when validation rule messages appear

Small markup fix

---

src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsViewModel.cs

---
- https://app.asana.com/0/0/1204337701409797

Added satellites bar

---

src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/PacketViewerView.axaml

StackPanel changed to DockPanel so that content would fit the desired window height
---
- https://app.asana.com/0/0/1204365171581184

Markup fixed so that filters can be scrolled

---

src/Asv.Drones.Gui/MainWindow.axaml.cs

---
- https://app.asana.com/0/0/1204337701409883

Maximize window state is saved in config

---

src/.idea/.idea.Asv.Drones/.idea/avalonia.xml
src/.idea/.idea.Asv.Drones/.idea/workspace.xml
src/Asv.Drones.Gui.Uav/Controls/AttitudeIndicator.axaml
src/Asv.Drones.Gui.Uav/RS.Designer.cs
src/Asv.Drones.Gui.Uav/RS.resx
src/Asv.Drones.Gui.Uav/RS.ru.resx

---
- https://app.asana.com/0/0/1204406391863518

Implemented velocity, altitude and compass tooltips

---

src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/Accuracy/AccuracyGbsRttViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/BaseStationMode/BaseStationModeGbsRttViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/DGpsRate/DGpsRateGbsRttViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/LinkQuality/LinkQualityGbsRttViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/Observation/ObservationGbsRttViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/VisibleSatellites/VisibleSatellitesGbsRttViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/Battery/BatteryUavRttViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/LinkQuality/LinkQualityUavRttViewModel.cs

---
- https://app.asana.com/0/0/1204429530426402

Checked and added ObserveOn for every rtt in UAV and GBS

---

src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavViewModel.cs

---
- https://app.asana.com/0/0/1204409706134794

Fixed anchors and polygons visibility identity

---

src/Asv.Drones.Gui.Uav/Controls/AttitudeIndicator.axaml
src/Asv.Drones.Gui.Uav/Controls/AttitudeIndicator.axaml.cs

---
- https://app.asana.com/0/0/1204415564037630

Changed angles for vertical progressbars

---

src/Asv.Drones.Gui.Core/RS.Designer.cs
src/Asv.Drones.Gui.Core/RS.resx
src/Asv.Drones.Gui.Core/RS.ru.resx
src/Asv.Drones.Gui.Core/Shell/Pages/Map/Flight/Logger/LoggerView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/Map/Flight/Logger/LoggerViewModel.cs

---
- https://app.asana.com/0/0/1204434904985358

Added clear flight logs button

---

src/Asv.Drones.Gui.Map/MapViewItem.axaml.cs

---
- https://app.asana.com/0/0/1204415564037614

Added hittestvisible check on selection

---

src/Asv.Drones.Gui.Core/RS.Designer.cs
src/Asv.Drones.Gui.Core/RS.resx
src/Asv.Drones.Gui.Core/RS.ru.resx
src/Asv.Drones.Gui.Core/Services/Navigation/NavigationService.cs
src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/Dialogs/SeparatorView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/Dialogs/SeparatorView.axaml.cs
src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/Dialogs/SeparatorViewModel.cs
src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/PacketViewerView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/PacketViewerViewModel.cs

---
- https://app.asana.com/0/0/1204269459180298

Added saving to csv

---

src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/PacketMessageViewModel.cs
src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/PacketViewerView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/PacketViewerViewModel.cs

---
- https://app.asana.com/0/0/1204268189581316

Added selection highlight to same type packets

---

src/Asv.Drones.Gui.Core/Controls/DigitIndicator.axaml
src/Asv.Drones.Gui.Core/Controls/DigitIndicator.axaml.cs
src/Asv.Drones.Gui.Core/Controls/StringIndicator.axaml
src/Asv.Drones.Gui.Core/Controls/StringIndicator.axaml.cs

---
- https://app.asana.com/0/0/1204434904985375

Added DigitIndicator and StringIndicator

---

src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/PacketViewerView.axaml

---
- https://app.asana.com/0/0/1204455172503852

Added horizontal scrollbar to packets listbox

---

src/Asv.Drones.Gui.Gbs/RS.Designer.cs
src/Asv.Drones.Gui.Gbs/RS.resx
src/Asv.Drones.Gui.Gbs/RS.ru.resx
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/GbsRttItem.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/IGbsRttItem.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/LinkQuality/LinkQualityGbsRttViewModel.cs
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/VisibleSatellites/VisibleSatellitesGbsRttViewModel.cs

Add minimize fuctionality to GBS widget
Asana: https://app.asana.com/0/1203851531040615/1204792540024837/f

Add GBS minimized widget

---

src/Asv.Drones.Gui.Uav/RS.Designer.cs
src/Asv.Drones.Gui.Uav/RS.resx
src/Asv.Drones.Gui.Uav/RS.ru.resx
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/Battery/BatteryUavRttViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/Gps/GpsUavRttViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/IUavRttItem.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/LinkQuality/LinkQualityUavRttViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Rtt/UavRttItem.cs

Add minimize fuctionality to UAV widget
https://app.asana.com/0/1203851531040615/1204365171581203/f

Add UAV minimized widget

---

src/Asv.Drones.Gui.Core/CorePlugin.cs
src/Asv.Drones.Gui.Core/CoreServicePlugin.cs
src/Asv.Drones.Gui.Core/Tools/IPluginEntryPoint.cs
src/Asv.Drones.Gui.Uav/UavPlugin.cs
src/Asv.Drones.Gui/App.axaml.cs
src/Asv.Drones.Gui/Asv.Drones.Gui.csproj
src/Asv.Drones.sln

---
- https://app.asana.com/0/0/1204833403564095

Add PROPRIETARY define for private plugins

---

src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageViewModel.cs

Check if there are any ruler anchors and show ruler icon only if anchors exist

Add ruler visibility check

---

src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavViewModel.cs

Fix for rtt items status update behavior
---
- https://app.asana.com/0/0/1204813013210474

fix (asv-drones): fix rtt items update

---

src/Asv.Drones.Gui.Uav/Controls/AttitudeIndicator.axaml

---
- https://app.asana.com/0/0/1204838602644333

fix(uav): fix attitude fonts

---

src/Asv.Drones.Gui.Core/RS.Designer.cs
src/Asv.Drones.Gui.Core/RS.resx
src/Asv.Drones.Gui.Core/RS.ru.resx
src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageViewModel.cs

Add localization for ruler map points selection
---
- https://app.asana.com/0/0/1204833403564066

fix(core): add ruler localization

---

src/Asv.Drones.Gui.Core/Shell/Pages/Map/IMap.cs
src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageViewModel.cs
src/Asv.Drones.Gui.Uav/RS.Designer.cs
src/Asv.Drones.Gui.Uav/RS.resx
src/Asv.Drones.Gui.Uav/RS.ru.resx
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavViewModel.cs

Add follow toggle button on UAV widget
---
- https://app.asana.com/0/0/1204337701409851

feat(uav): add follow button on UAV widget

---

src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Dialogs/RecordStartViewModel.cs

Add validation rule and clear of tag name and value after tag creation
Asana: https://app.asana.com/0/1203851531040615/1204858291398157/f

bug(sdr): fix tag name add method

---

src/Asv.Drones.Gui.Core/RS.Designer.cs
src/Asv.Drones.Gui.Core/RS.resx
src/Asv.Drones.Gui.Core/RS.ru.resx
src/Asv.Drones.Gui.Core/Services/Localization/ILocalizationService.cs
src/Asv.Drones.Gui.Core/Services/Localization/LocalizationServiceBase.cs
src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/DdmGp.cs
src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/DdmLlz.cs
src/Asv.Drones.Gui.Core/Shell/Pages/Settings/MeasureUnits/MeasureUnitsSettingsView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/Settings/MeasureUnits/MeasureUnitsSettingsViewModel.cs
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/DefaultSdrRttProvider.cs
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/GpSdrRttView.axaml
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/GpSdrRttView.axaml.cs
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/GpSdrRttViewModel.cs

This commit adds a new user interface for GP SDR in RTT mode. The UI is constructed using Avalonia library, and it features separate indicators for total power, DDM, SDM, AM90, AM150, PHI90, PHI150, Freq90, Freq150 in main section; total, CRS and CLR power under RF section. This allows users to monitor the data received from the SDR in real-time during flight. The addition of this feature will greatly enhance the navigational and diagnostic capabilities of the drone system. In addition, Measure unit settings for DDM GP were added. 
Asana: https://app.asana.com/0/1203851531040615/1204962408289037/f

feat(sdr): add SDR RTT interface for GP SDR

---

src/Asv.Drones.Gui.Core/RS.Designer.cs
src/Asv.Drones.Gui.Core/RS.resx
src/Asv.Drones.Gui.Core/RS.ru.resx
src/Asv.Drones.Gui.Core/Services/Localization/ILocalizationService.cs
src/Asv.Drones.Gui.Core/Services/Localization/LocalizationServiceBase.cs
src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Bearing.cs
src/Asv.Drones.Gui.Sdr/RS.Designer.cs
src/Asv.Drones.Gui.Sdr/RS.resx
src/Asv.Drones.Gui.Sdr/RS.ru.resx
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/DefaultSdrRttProvider.cs
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/GpSdrRttView.axaml
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/LlzSdrRttView.axaml
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/LlzSdrRttViewModel.cs
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/VorSdrRttView.axaml
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/VorSdrRttView.axaml.cs
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/VorSdrRttViewModel.cs

Modified canvas positions and grid sizes in GpSdrRttView, LlzSdrRttView, and VorSdrRttView for improved layout. Also updated colors for better visibility and contrast. These changes enhance user interface readability and overall user experience.
Asana: https://app.asana.com/0/1203851531040615/1204962408289039/f

feat(sdr): update layout and color scheme in GpSdrRttView, LlzSdrRttView and VorSdrRttView

---

src/Asv.Drones.Gui.Core/Asv.Drones.Gui.Core.csproj
src/Asv.Drones.Gui.Gbs/Asv.Drones.Gui.Gbs.csproj
src/Asv.Drones.Gui.Sdr/Asv.Drones.Gui.Sdr.csproj
src/Asv.Drones.Gui.Uav/Asv.Drones.Gui.Uav.csproj
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/Dialogs/SelectModeView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/Dialogs/SelectModeViewModel.cs

Updated flight mode icons and their alignments to improve UI consistency in `SelectModeViewModel.cs` and `SelectModeView.axaml` files. Also, skipped internal modes while listing available vehicle modes for better usability.
Updated Asv.Mavlink version to 3.2.5-alpha-17 in various `.csproj` files. This specific version is used for compatibility and new features that are necessary for the ongoing work.
Asana: https://app.asana.com/0/1203851531040615/1204961023189355/f

fix(uav): update UI and Asv.Mavlink version

---

src/Asv.Drones.Gui.Map/MapView.axaml
src/Asv.Drones.Gui.Map/MapView.axaml.cs

Updated the points for the polygon elements in MapView.axaml to be dynamically retrieved from the LeftCornerPoints and RightCornerPoints properties in the MapView.axaml.cs. This enables the polygonal shape to be changed dynamically through the respective properties. Also added a dialog mode in design mode for better UI representation.
Asana: https://app.asana.com/0/1203851531040615/1204967469316981/f

fix(map): update polygon points in MapView.axaml

---

src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Degrees.cs
src/Asv.Drones.Gui/Asv.Drones.Gui.csproj
src/Directory.Build.props

Updated the AsvCommonVersion to version 1.9.0-alpha-02 in Directory.Build.props for testing the latest alpha version features. Also, improved localization in the Drones GUI by replacing hardcoded string with resource string in Degrees.cs. Lastly, added the 'PROPRIETARY' constant to Debug and Release configurations in Asv.Drones.Gui.csproj to activate specific proprietary code paths.
Asana: https://app.asana.com/0/1203851531040615/1205102232827107/f
---
- https://app.asana.com/0/0/1205102232827105

fix: update AsvCommonVersion and improve localization

---

src/Asv.Drones.Gui.Core/Asv.Drones.Gui.Core.csproj
src/Asv.Drones.Gui.Core/Asv.Drones.Gui.Core.csproj.DotSettings
src/Asv.Drones.Gui.Core/RS.Designer.cs
src/Asv.Drones.Gui.Core/RS.resx
src/Asv.Drones.Gui.Core/RS.ru.resx
src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Degrees.cs
src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Latitude.cs
src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Longitude.cs
src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/DefaultHeaderToolsMenuProvider.cs
src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/Items/CoordinatesCalculator/CoordinatesCalculatorHelper.cs
src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/Items/CoordinatesCalculator/Dialog/CoordinatesCalculatorView.axaml
src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/Items/CoordinatesCalculator/Dialog/CoordinatesCalculatorView.axaml.cs
src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/Items/CoordinatesCalculator/Dialog/CoordinatesCalculatorViewModel.cs
src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/Items/CoordinatesCalculator/HeaderCoordinatesCalculatorMenu.cs
src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/ToolsMenuItem.cs
src/Asv.Drones.Gui.Core/Shell/ShellView.axaml
src/Asv.Drones.Gui.Uav/RS.resx
src/Asv.Drones.Gui.Uav/RS.ru.resx

Updated latitude, longitude, and altitude display units to use localized strings for better user accessibility. Refactored CoordinatesCalculatorView to reflect these changes. Also, several localization strings were updated to improve clarity and precision. The changes would support different measurements systems and better user experience for users in different regions.
Asana: https://app.asana.com/0/1203851531040615/1205097870344579/f

feat(core): update coordinate display units and localization.

---

src/Asv.Drones.Gui.Core/Shell/Pages/Map/Widgets/AnchorsEditorView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/Map/Widgets/AnchorsEditorViewModel.cs
src/Directory.Build.props

Updated the AsvCommonVersion to the latest 1.10.1-alpha-01 version in Directory.Build.props for better scalability and application performance. Also refactored AnchorsEditorViewModel in Asv.Drones.Gui.Core map widget interactions. Introduced '_internalChange' private boolean to ensure changes from one subscription do not affect the other subscriptions. This eliminates the repetitive unit assignation in all subscriptions. Also fixed the 'IsReadOnly' property binding in AnchorEditorView which was previously incorrectly inverted, thereby correcting the interaction with TextBoxes.
Asana: https://app.asana.com/0/1203851531040615/1205166500713016/f

Update AsvCommonVersion and refactor map widget interactions

---

src/Asv.Drones.Gui.Uav/Controls/MissionStatusIndicator.axaml.cs

Asana: https://app.asana.com/0/1203851531040615/1205290835733161/f

fix (uav(: fix nested subscription in MissionStatusIndicator.axaml.cs

---

src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsViewModel.cs

Asana: https://app.asana.com/0/1203851531040615/1205237266324945/f

fix(gbs): fix GBS widget correctly picking up the state of the base station

---

src/Asv.Drones.Gui/Asv.Drones.Gui.csproj
src/Asv.Drones.Gui/Views/MainWindow.axaml.cs

Update project settings to include Avalonia.Diagnostics package when using DebugPlugins and DebugLibs configurations. MainWindow.axaml.cs debug condition updated accordingly.
Asana: https://app.asana.com/0/1203851531040615/1205283152374517/f

fix: update project settings

---

src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapWidgetBase.cs
src/Asv.Drones.Gui.Map/MapView.axaml.cs
src/Asv.Drones.Gui.Map/MapViewItem.axaml.cs
src/Asv.Drones.Gui.Map/ViewModels/MapAnchorViewModel.cs
src/Asv.Drones.Gui.sln
src/Asv.Drones.Gui/App.axaml.cs
src/Asv.Drones.Gui/Asv.Drones.Gui.csproj

Add FlightDocs project reference to solution. Also add new attached property to MapView so that polygon can close in on itself.
Asana: https://app.asana.com/0/1203851531040615/1205100005725249/f

feat: add FlightDocs project reference

---

src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Degrees.cs

The Degrees measure unit was refactored to handle conversion and validation errors better. A new class, DegreesMeasureUnit, was extracted from the static array for better maintainability and to add better error checking, specifically in handling invalid string values. This will provide more meaningful error messages to the user and handle invalid inputs more robustly.
Asana: https://app.asana.com/0/1203851531040615/1205307075789342/f

fix(core): refactor Degrees measure unit for better error handling

---

src/Asv.Drones.Gui.Core/Shell/Pages/Map/Actions/AnchorMover/AnchorMoverActionView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/Map/Actions/AnchorMover/AnchorMoverActionView.axaml.cs
src/Asv.Drones.Gui.Core/Shell/Pages/Map/Actions/AnchorMover/AnchorMoverActionViewModel.cs
src/Asv.Drones.Gui.Map/MapView.axaml.cs
src/Asv.Drones.Gui.Map/MapViewItem.axaml.cs

This commit revises the map dragging feature in the Asv.Drones.Gui.Map project. Specifically, it refines the conditions that control how map items respond to pointer events, allowing for more precise handling. Additionally, this revision enforces the convention that a control key press must accompany pointer interactions for a dragging operation. The if-conditions were updated in both the 'MapView.axaml.cs' and 'MapViewItem.axaml.cs' files. Some redundant comments were also removed from 'MapViewItem.axaml.cs'. This change improves usability by providing more intuitive control over map items.
Asana: https://app.asana.com/0/1203851531040615/1205321974167938/f

feat(map): improve map dragging functionality

---

src/Asv.Drones.Gui.Uav/Asv.Drones.Gui.Uav.csproj.DotSettings
src/Asv.Drones.Gui.Uav/Controls/Converters/FloatToStringSafeConverter.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/QuickParamsSetup/Ardupilot/ArduCopter/Speeds/SpeedsQuickParamView.axaml
src/Asv.Drones.Gui.Uav/Shell/Pages/QuickParamsSetup/Ardupilot/ArduCopter/Speeds/SpeedsQuickParamViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/QuickParamsSetup/DefaultQuickParamsPartProvider.cs

Added try-catch statements in SpeedsQuickParamViewModel.cs functions that interact with the vehicle parameters. This will mitigate unhandled exceptions when reading from or writing to the vehicle parameters by logging an error message instead. Also, made minor updates to enhance floating point to string conversions for the text boxes in SpeedsQuickParamView.axaml. This update improves the overall robustness and performance of the application.
Asana: https://app.asana.com/0/1203851531040615/1205371221383398/f

fix(uav): update code to enhance error handling in speed parameter view

---

src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavViewModel.cs

In the FlightUavViewModel, our FollowUavCommand has been expanded with a conditional check. This allows us to ensure that if an ItemToFollow is currently selected on the Map, it will be deselected and the IsFollowed flag will be set to false.
This change improves the way our app handles user interactions with FollowUavCommand and it makes our UAV flight tracking logic more robust and straightforward. By only setting IsFollowed and ItemToFollow when a UAV vehicle is found, we avoid potential issues where the map might attempt to follow a non-existent or null item.
Asana: https://app.asana.com/0/1203851531040615/1205371221383408/f

fix (uav): add conditional check to FollowUavCommand in FlightUavViewModel

---

src/Asv.Drones.Gui.Core/RS.Designer.cs
src/Asv.Drones.Gui.Core/RS.resx
src/Asv.Drones.Gui.Core/RS.ru.resx
src/Asv.Drones.Gui.Core/Services/Localization/ILocalizationService.cs
src/Asv.Drones.Gui.Core/Services/Localization/LocalizationServiceBase.cs
src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/FieldStrength.cs

New measurement unit for field strength has been added. Field strength related strings were introduced into the resources file for localization. These include the field strength title, measurement unit, and description. This is done to aid in data interpretation and localization.
Asana: https://app.asana.com/0/1203851531040615/1205537326923774/f

feat: add field strength localization and measurement unit

---

src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/FlightSdrViewModel.cs

Asana: https://app.asana.com/0/1203851531040615/1205665177302087/f

fix (sdr): fix SDR record name generation

---

src/Asv.Drones.Gui/App.axaml.cs

Separated plugin loading logic into different sections for IClassicDesktopStyleApplicationLifetime and ISingleViewApplicationLifetime in App.axaml.cs. This change was necessary to handle different plugin behaviors on different platforms. Additionally, added AndroidCatalogs to handle dynamic plugin loading for Android platform.
Asana: https://app.asana.com/0/1203851531040615/1205666798678866/f

fix (android): refactored plugin loading for Android and desktop platforms

---

src/Asv.Drones.Gui.Uav/Shell/Pages/QuickParamsSetup/Ardupilot/ArduCopter/ControllerReload/ControllerReloadQuickParamViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/QuickParamsSetup/Ardupilot/ArduCopter/Identity/IdentityQuickParamViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/QuickParamsSetup/Ardupilot/ArduCopter/Speeds/SpeedsQuickParamViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/QuickParamsSetup/DefaultQuickParamsPartProvider.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/QuickParamsSetup/QuickParamsSetupPageViewModel.cs

This commit introduces a number of changes across various ViewModel classes to improve error handling and streamline parameter setup. Specifically, unnecessary code references have been removed and logging services have been included in some constructors for better tracking of setup processes. In addition, certain functions have been moved out of the command creation process to enhance readability and management of cancellation tokens. These changes are aimed at improving code stability and maintainability.
Asana: https://app.asana.com/0/1203851531040615/1205990900962997/f

fix: refactor code for parameter setup and error handling

---

src/Asv.Drones.Gui.Core/Controls/HierarchicalStore/HierarchicalStoreView.axaml
src/Asv.Drones.Gui.Core/RS.Designer.cs
src/Asv.Drones.Gui.Core/RS.resx
src/Asv.Drones.Gui.Core/RS.ru.resx
src/Asv.Drones.Gui.Core/Services/MavlinkDevices/MavlinkHelper.cs
src/Asv.Drones.Gui.Core/Shell/Pages/Map/HeaderAnchorsMenu.cs
src/Asv.Drones.Gui.Core/Shell/Pages/Map/Widgets/AnchorsEditorView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/PacketViewerView.axaml
src/Asv.Drones.Gui.Gbs/RS.Designer.cs
src/Asv.Drones.Gui.Gbs/RS.resx
src/Asv.Drones.Gui.Gbs/RS.ru.resx
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsView.axaml
src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Rtt/DGpsRate/DGpsRateGbsRttViewModel.cs
src/Asv.Drones.Gui.Sdr/RS.Designer.cs
src/Asv.Drones.Gui.Sdr/RS.resx
src/Asv.Drones.Gui.Sdr/RS.ru.resx
src/Asv.Drones.Gui.Sdr/Shell/Pages/Store/SdrStorePageViewModel.cs
src/Asv.Drones.Gui.Sdr/Shell/Pages/Store/SdrStoreShellMenuItem.cs
src/Asv.Drones.Gui.Uav/RS.Designer.cs
src/Asv.Drones.Gui.Uav/RS.resx
src/Asv.Drones.Gui.Uav/RS.ru.resx
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/GoToMapAnchorActionViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/LandAnchorActionViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/RoiAnchorActionViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/RtlAnchorActionViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/StartAutoAnchorActionViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/TakeOffAnchorActionViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/Attitude/AttitudeViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/Planing/Widgets/Mission/PlaningMissionViewModel.cs
src/Asv.Drones.Gui.Uav/Shell/Pages/VehiclesShellMenuItemProvider.cs

In this commit. Added russian language values to UI of Asv.Drones.Gui.Core views.
Full localized Asv.Drones.Gui.Uav fields in files:
• SdrStorePageViewModel
• SdrStoreShellMenuItem
• GoToMapAnchorActionViewModel
• RtlAnchorActionViewModel
• SdrStorePageViewModel
Full localized Asv.Drones.Gui.Gbs fields in files:
•DGpsRateGbsRttViewModel
Asana: https://app.asana.com/0/1203851531040615/1205858132448005/f

feat: localization added 

---

src/Asv.Drones.Gui.Custom.props

Asana:https://app.asana.com/0/1203851531040615/1206045363552297/f
---
- https://app.asana.com/0/0/1206119584243562

feat: update avalonia to 11.0.5

---

src/Asv.Drones.Gui.Core/RS.Designer.cs
src/Asv.Drones.Gui.Core/RS.resx
src/Asv.Drones.Gui.Core/RS.ru.resx
src/Asv.Drones.Gui.Core/Shell/Pages/Parameters/ParamItemViewModel.cs
src/Asv.Drones.Gui.Core/Shell/Pages/Parameters/ParamPageView.axaml
src/Asv.Drones.Gui.Core/Shell/Pages/Parameters/ParamPageViewModel.cs

Added "Cancel" button under parameters loading progress bar. If button pressed the loading progress hides.That allow begin work with already loaded params without load end wait.
Asana: https://app.asana.com/0/1203851531040615/1205820505097233/f

Drone parameters cancel button added

---

src/Asv.Drones.Gui.Core/Controls/HierarchicalStore/HierarchicalStoreView.axaml
src/Asv.Drones.Gui.Core/RS.resx
src/Asv.Drones.Gui.Core/RS.ru.resx

Added localized tooltips for Refresh, Create new Folder, Create New File buttons.
Asana: https://app.asana.com/0/1203851531040615/1206243159897177/f

feat: HierarchicalStoreView buttons now have tooltips

---

src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/GpSdrRttViewModel.cs
src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/LlzSdrRttViewModel.cs

fix (asv-drones-gui-sdr): change Phi90StringValue
Change Phi90StringValue for GP and LLz in SDR widget
Asana: https://app.asana.com/0/1203851531040615/1206315304108737/f

fix-asv-drones-gui-PHI90-value

---

src/Asv.Drones.Gui.Core/RS.Designer.cs

Fixed missed resource value public names

fix: update RS.Designer.cs in Asv.Drones.Gui.Core

---

src/Asv.Drones.Gui/Views/MainWindow.axaml.cs

fix bug with window transparency
Asana: https://app.asana.com/0/1203851531040615/1205906196019636/f

fix(asv-drones): fix mica effect

---

src/Asv.Drones.Gui.Map/MapView.axaml.cs

Fixed event OnPointerPressed with only right mouse button check for disabling ruler.

Fix (map): fix ruler off on left mouse button

---

src/Asv.Drones.Gui.Api/Tools/Controls/Map/Actions/Mover/MapMoverActionView.axaml.cs

feat(mover): remove hotkey from MapMoverActionView
asana: https://app.asana.com/0/1203851531040615/1207177981218323/f

feat(mover): remove hotkey from MapMoverActionView

---

src/Asv.Drones.Gui.Api/Tools/Controls/Map/Widgets/AnchorEditor/AnchorsEditorView.axaml
src/Asv.Drones.Gui.Api/Tools/Controls/Map/Widgets/AnchorEditor/AnchorsEditorView.axaml.cs
src/Asv.Drones.Gui.Api/Tools/Controls/Map/Widgets/AnchorEditor/AnchorsEditorViewModel.cs
src/Directory.Build.props

Asana: https://app.asana.com/0/1206009821057985/1207177981218317/f

feat(anchor-editor): add vehicle actions and new style

---

src/Asv.Drones.Gui/Shell/ShellViewModel.cs

---
- https://app.asana.com/0/0/1207411924258632

Popup Messages limit (3)

---

src/Asv.Drones.Gui.Api/Tools/Controls/Map/Widgets/AnchorEditor/AnchorsEditorView.axaml

fix(anchor editor): add icon margin in actions
asana: https://app.asana.com/0/1203851531040615/1207643849991134/f

fix(anchor editor): add icon margin in actions

---

src/Asv.Drones.Gui/Shell/Pages/Flight/Widgets/Uav/FlightUavView.axaml

fix(Uav): move the mode button
asana: https://app.asana.com/0/1203851531040615/1207643849991144/f

fix(Uav): move the mode button

---

src/Asv.Drones.Gui/Services/LogService/LogService.cs

Asana: https://app.asana.com/0/1206009821057985/1207643849991142/f

fix(log-service):add filters to different levels of errors according to Nlog documentation. Add Logger message save

---

src/Asv.Drones.Gui.Api/Tools/Controls/HierarchicalStore/HierarchicalStoreView.axaml

Asana: https://app.asana.com/0/1203851531040615/1207644963134958/f

fix(hierarchical-store): add scroll viewer at list of tasks

---

src/Asv.Drones.Gui/Shell/Pages/Flight/Widgets/Uav/FlightUavView.axaml
src/Asv.Drones.Gui/Shell/Pages/Flight/Widgets/Uav/MissionStatus/MissionStatusView.axaml
src/Asv.Drones.Gui/Shell/Pages/Flight/Widgets/Uav/MissionStatus/MissionStatusViewModel.cs

Asana: https://app.asana.com/0/1203851531040615/1207644963134966/f

fix: progress bar

---

.github/workflows/ApiReleaseDeployActionGitHubOnly.yml
src/Asv.Drones.Gui.Api/Asv.Drones.Gui.Api.csproj

Asana: https://app.asana.com/0/1203851531040615/1207693167811054/f

feat: add api release action for GitHub+Nuget and GitHub only

---

src/Asv.Drones.Gui.Api/Tools/Controls/Map/Widgets/AnchorEditor/AnchorsEditorView.axaml

Asana: https://app.asana.com/0/1206009821057985/1207659349298630/f

fix(anchor-editor): inactive actions collapse from visual

---

src/Asv.Drones.Gui.Api/RS.Designer.cs
src/Asv.Drones.Gui.Api/RS.resx
src/Asv.Drones.Gui.Api/RS.ru.resx
src/Asv.Drones.Gui.Api/Tools/Controls/Map/Widgets/AnchorEditor/AnchorsEditorViewModel.cs
src/Asv.Drones.Gui/RS.Designer.cs
src/Asv.Drones.Gui/RS.resx
src/Asv.Drones.Gui/RS.ru.resx
src/Asv.Drones.Gui/Shell/Pages/Flight/Widgets/Logger/LoggerViewModel.cs
src/Asv.Drones.Gui/Shell/Pages/Flight/Widgets/Uav/MissionStatus/MissionStatusView.axaml
src/Asv.Drones.Gui/Shell/Pages/Settings/Appearance/AppearanceTreeMenuItem.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Installed/PluginsInstalledView.axaml
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketTreeMenuItem.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketView.axaml
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Sources/PluginsSourcesTreeMenuItem.cs

- remove unused resources
- add localization for UAV and Setings
asana: https://app.asana.com/0/1206118975886649/1207664869860715/f

fix(localization): refactor localization

---

src/Asv.Drones.Gui/Shell/ShellView.axaml
src/Asv.Drones.Gui/Shell/ShellViewModel.cs

asana: https://app.asana.com/0/1206118975886649/1207753631316463/f

Fix(shell menu): add checkout for SelectedMenu in method GoTo

---

src/Asv.Drones.Gui/Services/Localization/MeasureUnits/Distance.cs

- Added DistanceMeasureUnit class implementing IMeasureUnitItem<double, DistanceUnits>
- Integrated DistanceMeasureUnit into _units array in Distance class
asana: https://app.asana.com/0/1206118975886649/1207784235084607/f

fix(MeasureUnits): refactor Distance class and add DistanceMeasureUnit class

---

src/Asv.Drones.Gui/Services/Mavlink/MavlinkDevicesService.cs
src/Directory.Build.props

asana: https://app.asana.com/0/1203851531040615/1207975956031500/f

feat(api): update MAVlink to version 3.10.2

---

src/Asv.Drones.Gui/Services/Localization/MeasureUnits/Distance.cs

fix incorrect mission calculation in Distance method Print and PrintWithUnits
asana: https://app.asana.com/0/1206118975886649/1207987623015215/f

fix(MeasureUnits): fix incorrect mission calculation

---

src/Asv.Drones.Gui/RS.Designer.cs
src/Asv.Drones.Gui/RS.resx
src/Asv.Drones.Gui/RS.ru.resx
src/Asv.Drones.Gui/Shell/Pages/Settings/Connection/Ports/Dialogs/SerialPortView.axaml
src/Asv.Drones.Gui/Shell/Pages/Settings/Connection/Ports/Dialogs/TcpPortView.axaml
src/Asv.Drones.Gui/Shell/Pages/Settings/Connection/Ports/Dialogs/UdpPortView.axaml

asana: https://app.asana.com/0/1206118975886649/1207599808860376/f

feat(setting): add slider in SerialPortView, TcpPortView and UdpPortView

---

src/Asv.Drones.Gui/Shell/Pages/Flight/Widgets/Uav/MissionStatus/MissionStatusViewModel.cs

asana: https://app.asana.com/0/1206118975886649/1208033523549218/f

fix(uav): fix bug with progress bar when goto is called

---

src/Asv.Drones.Gui.Api/Services/Localization/IMeasureUnit.cs

Asana: https://app.asana.com/0/1203851531040615/1207778336920911/f

fix: make measure unit return some default message instead of a null

---

src/Directory.Build.props

Asana: https://app.asana.com/0/1206009821057985/1207986882522777/f

fix(build-props): new mavlink version

---

src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketView.axaml

asana: https://app.asana.com/0/1203851531040615/1206817732447468/f

feat(Market): add ProgressBar when plugin is installing

---

src/Asv.Drones.Gui/RS.Designer.cs
src/Asv.Drones.Gui/RS.resx
src/Asv.Drones.Gui/RS.ru.resx
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Installed/InstalledPluginInfoViewModel.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Installed/PluginsInstalledView.axaml
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginInfoViewModel.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketView.axaml
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketViewModel.cs

asana: https://app.asana.com/0/1203851531040615/1206817732447459/f

feat(market): add new tag Unverified

---

src/Asv.Drones.Gui/Asv.Drones.Gui.csproj
src/Asv.Drones.Gui/Services/Plugins/PluginManager.cs

Asana: https://app.asana.com/0/1203851531040615/1208071841070110/f
---
- https://app.asana.com/0/0/1208103950254289

feat: add ability to extract content folder from nuget package

---

src/Asv.Drones.Gui.Api/CompatibilitySuppressions.xml
src/Asv.Drones.Gui.Api/Services/Plugins/IPluginManager.cs
src/Asv.Drones.Gui.Api/Services/Plugins/IPluginManuallyInstallable.cs
src/Asv.Drones.Gui.Api/Services/Plugins/NullPluginManager.cs
src/Asv.Drones.Gui.Desktop/Asv.Drones.Gui.Desktop.csproj
src/Asv.Drones.Gui/Asv.Drones.Gui.csproj.DotSettings
src/Asv.Drones.Gui/RS.Designer.cs
src/Asv.Drones.Gui/RS.resx
src/Asv.Drones.Gui/RS.ru.resx
src/Asv.Drones.Gui/Services/Plugins/PluginManager.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/Dialogs/PluginInstaller.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/Dialogs/PluginInstallerView.axaml
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/Dialogs/PluginInstallerView.axaml.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/Dialogs/PluginInstallerViewModel.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginInfoViewModel.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketTreeMenuItem.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketView.axaml
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketView.axaml.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketViewModel.cs

Asana: https://app.asana.com/0/1203851531040615/1208157082872507/f

feat: add manual plugin installation

---

src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginInfoViewModel.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketView.axaml

asana: https://app.asana.com/0/1203851531040615/1206817732447464/f

feat(market): separately show installed version plugin

---

src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginInfoViewModel.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketView.axaml

asana: https://app.asana.com/0/1203851531040615/1206817732447464/f
---
- https://app.asana.com/0/0/1206817732447467

feat(market): refactor commands Install/Uninstall

---

src/Asv.Drones.Gui.Api/Tools/Converters/StringToDecimalConverter.cs
src/Asv.Drones.Gui/Shell/Pages/Flight/Anchors/Uav/Actions/TakeOff/UavActionTakeOff.cs
src/Asv.Drones.Gui/Shell/Pages/Flight/Dialogs/TakeOffView.axaml
src/Asv.Drones.Gui/Shell/Pages/Flight/Dialogs/TakeOffView.axaml.cs
src/Asv.Drones.Gui/Shell/Pages/Flight/Dialogs/TakeOffViewModel.cs

Asana:
https://app.asana.com/0/1207431474362030/1206462231162019/f

Altitude increment buttons

---

src/Asv.Drones.Gui.Api/CompatibilitySuppressions.xml
src/Asv.Drones.Gui.Api/Services/Plugins/ILocalPluginInfo.cs
src/Asv.Drones.Gui/Services/Plugins/LocalPluginInfo.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Installed/InstalledPluginInfoViewModel.cs
src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Installed/PluginsInstalledView.axaml

add property for icons and functional for getting icons
asana: https://app.asana.com/0/1203851531040615/1206817732447462/f

feat(market)add icons in plugin market

---

src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketView.axaml

asana: https://app.asana.com/0/1203851531040615/1208233210004203/f

fix(market): remove ListBox in Additional info page

---

src/Asv.Drones.Gui.Desktop/Asv.Drones.Gui.Desktop.csproj
src/Asv.Drones.Gui/Asv.Drones.Gui.csproj
src/Directory.Build.props

Asana: https://app.asana.com/0/1203851531040615/1208539887289678/f

feat: update versions of NuGet.Packaging and System.IO.Packaging

---

.github/workflows/BuildForWindows.yml
.github/workflows/build-macOS-arm64.yml
.github/workflows/release-action.yml
README.md
build-dmg-arm64.sh
bundle-mac-app.sh
src/Asv.Drones.Gui.Desktop/Asv.Drones.Gui.Desktop.csproj
src/Asv.Drones.Gui.Desktop/Info.plist
src/Asv.Drones.Gui.sln
src/Asv.Drones.Gui/Asv.Drones.Gui.csproj

Add .sh scripts for local dmg build, update readme, change workflow release logic, add UrlScheme to open app from browser.
Asana: https://app.asana.com/0/1203851531040615/1208557050126452/f

feat: add workflow for macOS (arm64) dmg file build

---

src/Asv.Drones/Pages/Flight/Widgets/UavWidget/Dialogs/SetAltitudeDialog.axaml
src/Asv.Drones/Pages/Flight/Widgets/UavWidget/Dialogs/SetAltitudeDialogViewModel.cs
src/Asv.Drones/Pages/Flight/Widgets/UavWidget/MissionProgress/MissionProgressView.axaml
src/Asv.Drones/Pages/Flight/Widgets/UavWidget/MissionProgress/MissionProgressViewModel.cs
src/Asv.Drones/Pages/Flight/Widgets/UavWidget/UavWidgetView.axaml
src/Asv.Drones/Pages/Flight/Widgets/UavWidget/UavWidgetViewModel.cs

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210056639757452?focus=true

fix: unit symbol display

---

src/Asv.Drones/Asv.Drones.csproj.DotSettings
src/Asv.Drones/Commands/Flight/Widgets/UavWidget/AutoModeCommand.cs
src/Asv.Drones/Commands/Flight/Widgets/UavWidget/GuidedModeCommand.cs
src/Asv.Drones/Commands/Flight/Widgets/UavWidget/LandCommand.cs
src/Asv.Drones/Commands/Flight/Widgets/UavWidget/RTLCommand.cs
src/Asv.Drones/Commands/Flight/Widgets/UavWidget/StartMissionCommand.cs
src/Asv.Drones/Commands/Flight/Widgets/UavWidget/TakeOffCommand.cs

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210109530505375?focus=true

feat: make uav widget commands async

---

src/Asv.Drones/Pages/Flight/Anchors/FlightUavAnchorsExtension.cs
src/Asv.Drones/Pages/Flight/Widgets/UavWidget/MissionProgress/MissionProgressViewModel.cs
src/Asv.Drones/Pages/Flight/Widgets/UavWidget/UavWidgetViewModel.cs
src/Asv.Drones/Pages/MavParams/MavParamsPageViewModel.cs
src/Asv.Drones/RS.Designer.cs
src/Asv.Drones/RS.resx
src/Asv.Drones/RS.ru.resx
src/Directory.Build.props

cannot fix the bug
update version to 2.0.0-dev.2 (api and drones)

feat: add localization to UavWidgetViewModel

---

.github/workflows/api-release-dev.yml
.github/workflows/api-release.yml

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210720452444090?focus=true

ci: update api workflow to work with lang prev

---

.github/workflows/api-release-dev.yml
.github/workflows/api-release.yml
.github/workflows/drones-release-windows.yml
src/Asv.Drones.Android/Asv.Drones.Android.csproj
src/Asv.Drones.Api/Asv.Drones.Api.csproj
src/Asv.Drones.Desktop/Asv.Drones.Desktop.csproj
src/Asv.Drones.iOS/Asv.Drones.iOS.csproj
src/Asv.Drones/App.axaml.cs
src/Asv.Drones/Asv.Drones.csproj
src/Asv.Drones/Pages/FileBrowser/FileBrowserView.axaml
src/Asv.Drones/Pages/PacketViewer/PacketViewerView.axaml
src/Directory.Build.props

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210902613481121?focus=true

feat: update to dotnet core 9

---

src/Asv.Drones.Android/Asv.Drones.Android.csproj
src/Asv.Drones.Api/Asv.Drones.Api.csproj
src/Asv.Drones.Desktop/Asv.Drones.Desktop.csproj
src/Asv.Drones.iOS/Asv.Drones.iOS.csproj
src/Asv.Drones/Asv.Drones.csproj
src/Directory.Build.props

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1211194034054324?focus=true

feat: update Asv.Avalonia, Asv.Mavlink, Asv.Gnss

---

src/Asv.Drones.sln
src/Asv.Drones/Pages/Flight/Widgets/UavWidget/UavWidgetViewModel.cs
src/Directory.Build.props

make design renderable for the uav widget
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1211494432886562?focus=true

fix: update asv.avalonia to v1.0.3-dev.16
