src/Asv.Drones.Gui.Core/Shell/Pages/Map/Flight/FlightPageView.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageView.axaml.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Map/Planing/PlaningPageView.cs
Error occured if column definitions contained fractional numbers. In this case TryParse returns 0 and Grid columns become essentially invisible.
Fractional numbers were generated because of Windows global zoom settings. If they are different from 100%, then pixel size can become fractional.
To resolve the issue we take the restored value and drop it's fractional part before parsing.
---
- https://app.asana.com/0/0/1204337701409804
=> Widget size is now correctly restored from config

src/Asv.Drones.Gui/MainWindow.axaml.cs
If window position is out of bounds, it will be set to top left corner of main screen. If window is bigger than all screens, it will be set to be 90% of the main screen and it's position set to be in top left corner of primary screen.
---
- https://app.asana.com/0/0/1204337701409792
=> Changes to how screen position and size is restored from config

src/Asv.Drones.Gui.Core/Shell/Pages/Connections/Ports/Dialogs/SerialPortViewModel.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Connections/Ports/Dialogs/TcpPortViewModel.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Connections/Ports/Dialogs/UdpPortViewModel.cs
Enabled the connections by default in TcpPortViewModel, SerialPortViewModel, and UdpPortViewModel on initialization by changing "IsEnabled" attribute from false to true. This simplifies the user experience by making connections active as soon as they are created instead of requiring users to manually activate them.
=> fix(core): enable connections by default on creation or edit

.github/workflows/macos_release.yml, .github/workflows/ubuntu_release.yml, .github/workflows/windows_release.yml
Added a `dotnet workload restore` command in the restore dependencies step for macOS, Ubuntu, and Windows release workflows. This is necessary to ensure the correct dotnet workload is restored before dependency restoration for better build success.
Asana: https://app.asana.com/0/1203851531040615/1204953971605260/f
=> fix: add dotnet workload restore in ci workflows

src/Asv.Drones.Gui.Uav/Controls/AttitudeIndicator.axaml, src/Asv.Drones.Gui.Uav/Controls/AttitudeIndicator.axaml.cs
Introduced Styled Properties for different PolygonPoints (Altitude, Velocity, Roll, Home) in the AttitudeIndicator component. It allows points of polygons to be changed dynamically. This was necessary due to an issue with Avalonia's handling of nullable Point attributes, requiring us to set up static points for components through C# code-behind until the issue is resolved in the Avalonia framework. Also, references in XAML were updated to reflect these changes.
Asana: https://app.asana.com/0/1203851531040615/1204953971605269/f
=> fix(uav): add polygon styled properties to AttitudeIndicator component

src/Asv.Drones.Gui.Core/CorePlugin.cs
Adjusted the author and application URLs in CorePlugin.cs to match changes in website domains. The author URL is changed from the Github profile to a personal website, and the app URL is now directing to the documentation site instead of the Github repository. This is to provide more accurate and helpful information to the users.
Asana: https://app.asana.com/0/1203851531040615/1204953971605265/f
=> fix(core): update author and app URLs in CorePlugin.cs

src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/Dialogs/RebootAutopilotView.axaml, src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/RebootAutopilotAnchorActionViewModel.cs
Changed the ContentDialog title to use a resource string which provides better context. Replaced the Grid layout with a StackPanel in RebootAutopilotView.axaml for easier maintainability and readability. It formats the components vertically with a separation, providing a cleaner visual structure than before.
Asana: https://app.asana.com/0/1203851531040615/1204953971605291/f
=> fix(uav): update layout and title of RebootAutopilotView

src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/Dialogs/SelectModeView.axaml
A tooltip field has been added to the grid in SelectModeView.axaml. This change was made to provide descriptions for each mode, enhancing user understanding of each option. The tooltip is being populated with the compiled binding of each mode's description.
Asana: https://app.asana.com/0/1203851531040615/1204953971605284/f
=> fix(uav): add tooltips to grid in SelectModeView

src/Asv.Drones.Gui/App.axaml.cs
Modified App.axaml.cs file to prevent plugin loading during design time. This was done by checking the status of DesignMode and if true, clearing the _plugins. This change increases efficiency as plugins are not needed during design time.
Asana: https://app.asana.com/0/1203851531040615/1204963250497035/f
---
- https://app.asana.com/0/0/1204963250497035
=> fix: prevent plugin loading in design mode

src/Asv.Drones.Gui.Core/Controls/OptionsDisplayItem/OptionsDisplayItemStyles.axaml, src/Asv.Drones.Gui/App.axaml
Added DynamicResource TextFillPrimaryColorBrush as the Foreground value to TextBlock and MaterialIcon Style selectors in App.axaml file. The change has also been made to OptionsDisplayItemStyles.axaml file. This update ensures text and icons across the application use the primary color defined in the theme for consistency and better visual hierarchy.
Asana: https://app.asana.com/0/1203851531040615/1204953970281511/f
=> fix: update color scheme for TextBlocks and MaterialIcons

src/Asv.Drones.Gui.Core/Shell/Pages/Connections/Ports/ConnectionsPortsViewModel.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Connections/Ports/PortViewModel.cs, src/Asv.Drones.Gui.Core/Shell/Pages/PacketViewer/PacketViewerViewModel.cs, src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/Dialogs/FixedModeViewModel.cs, src/Asv.Drones.Gui.Gbs/Shell/Pages/Flight/Widgets/Gbs/FlightGbsViewModel.cs, src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/FlightSdrViewModel.cs, src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/RebootAutopilotAnchorActionViewModel.cs, src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/SelectModeAnchorActionViewModel.cs, src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Layers/Anchors/UavAnchor/Actions/TakeOffAnchorActionViewModel.cs, src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavViewModel.cs
This commit updates ViewModel initialization across various files to use 'using' declarations, thus ensuring that the objects gets properly disposed to free resources. This change makes the code cleaner and more memory efficient, as the declared variables doesn't have the chance to escape their scope and can be immediately disposed of when they're no longer in use.
Asana: https://app.asana.com/0/1203851531040615/1204971171054340/f
=> fix: refactor ViewModel initialization to use using declarations

src/Asv.Drones.Gui.Core/Shell/Pages/Map/Actions/Ruler/MapRulerActionViewModel.cs
The default state of the ruler when the map is loaded has been changed from visible to hidden. This is to improve the initial user experience by reducing clutter and promoting a cleaner UI. Further interactions with the ruler can be made by the user as needed.
Asana: https://app.asana.com/0/1203851531040615/1205041729023507/f
=> fix: change default ruler visibility upon map loading

src/Asv.Drones.Gui/App.axaml
In the Asv.Drones.Gui application, additional styling has been provided for both TextBlock and MaterialIcon when in disabled state. These new styles update the foreground color to utilize the `TextFillColorDisabledBrush` dynamic resource instead of the regular `TextFillColorPrimaryBrush`, aiming to provide a better visual hint on element's state to users.
Asana: https://app.asana.com/0/1203851531040615/1205007794960756/f
=> fix: add styles for disabled TextBlock and MaterialIcon

src/Asv.Drones.Gui.Sdr/RS.Designer.cs, src/Asv.Drones.Gui.Sdr/RS.resx, src/Asv.Drones.Gui.Sdr/RS.ru.resx, src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/FlightSdrView.axaml, src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/FlightSdrViewModel.cs, src/Asv.Drones.Gui/Asv.Drones.Gui.csproj
This commit introduces two new system control actions: 'Reboot OS' and 'Shutdown OS' to the flight SDR view. The changes include necessary updates in related view models and localized strings for both English and Russian language. These actions provide a user with a capability to safely reboot or shutdown the operating system from the user interface. The new controls are designed as options in a dropdown menu for convenience.
Asana: https://app.asana.com/0/1203851531040615/1205007794960754/f
=> feat(sdr): add safe OS reboot and shutdown commands

src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/FlightUavViewModel.cs
The map's UAV widget follow state was not being properly updated when the map item to follow was set to null. This change ensures that all of the UAV widgets are set to 'not followed' when the map item to follow is made null. This will prevent inconsistencies in the follow-status between the map and the UAV widgets.
Asana: https://app.asana.com/0/1203851531040615/1205044822709643/f
=> fix(uav): update Map follow state for UAV widgets

src/Asv.Drones.Gui.Core/Services/Theme/IThemeService.cs, src/Asv.Drones.Gui.Core/Services/Theme/ThemeService.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Settings/Theme/SettingsThemeView.axaml, src/Asv.Drones.Gui.Core/Shell/Pages/Settings/Theme/SettingsThemeViewModel.cs, src/Asv.Drones.Gui.Core/Shell/ShellView.axaml, src/Asv.Drones.Gui.Core/Shell/ShellView.axaml.cs, src/Asv.Drones.Gui.Core/Shell/ShellViewModel.cs
An `OnLoaded` event handler has been added to `ShellView.axaml.cs`. This allows `ShellViewModel` to load the theme from the config once the view is loaded. The `IThemeService` and `IConfiguration` dependencies were also added to the `ShellViewModel` constructor. This ensures that the preferred theme is applied when the ShellView is being rendered.
Also, the FlowDirection feature was removed from the ThemeService and all related implementations. This isn't necessary for the current functionalities of our application. This change simplifies the code by reducing redundant elements, focusing only on necessary features and also improves readability of the code. Future enhancements can consider adding it back if needed.
Asana: https://app.asana.com/0/1203851531040615/1204953970281515/f
---
- To …
=> fix (core): fix startup theme on Android

src/Asv.Drones.Gui.Core/RS.Designer.cs, src/Asv.Drones.Gui.Core/RS.resx, src/Asv.Drones.Gui.Core/RS.ru.resx, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Altitude.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/AmplitudeModulation.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Bearing.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/DdmGp.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/DdmLlz.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Degrees.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Distance.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Frequency.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/IMeasureUnit.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Latitude.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Longitude.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/MeasureUnitBase.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Phase.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Power.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Sdm.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Temperature.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Velocity.cs
In this commit, we replaced the hardcoded string descriptions for various measure units with their respective localized equivalents from the resources file (RS). This change was necessary for multi-language support. Ensuring these descriptions are localized ensures the application's UI is accurately and appropriately presented for users in different locales.
Asana: https://app.asana.com/0/1203851531040615/1205157700476802/f
=> feat (core): update measure unit descriptions for localization

src/Asv.Drones.Gui.Core/Shell/Pages/Connections/Ports/PortView.axaml
Updated TextBlocks in PortView.axaml to prevent text overflow. 'Name' and 'ConnectionString' fields are now set to 'NoWrap', ensuring proper visibility and readability on fixed layout.
Asana: https://app.asana.com/0/1203851531040615/1205134815539037/f
=> fix(core): prevent text overflow in PortView.axaml

src/Asv.Drones.Gui.Sdr/RS.Designer.cs, src/Asv.Drones.Gui.Sdr/RS.resx, src/Asv.Drones.Gui.Sdr/RS.ru.resx, src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Dialogs/RecordStartView.axaml, src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Dialogs/RecordStartViewModel.cs, src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/FlightSdrViewModel.cs
Changed the frequency validation logic in `FlightSdrViewModel.cs` to directly validate the frequency input as a number greater than zero, instead of using _freqInMHzMeasureUnit.IsValid(_). This was done to simplify and improve the speed of validation, removing the need to convert and validate the input through the measure unit methods.
Hardcoded strings in the 'RecordStartViewModel.cs', 'RecordStartView.axaml', and 'FlightSdrViewModel.cs' files were replaced with localized resources for improving the localization support. This ensures that the respective file displays appropriate messages, placeholders, button texts etc. in different languages based on the user's locale.
Asana: https://app.asana.com/0/1203851531040615/1205134815539121/f
=> feat (sdr): update frequency validation in FlightSdrViewModel and replace hardcoded strings with localized resources

src/Asv.Drones.Gui.Core/Asv.Drones.Gui.Core.csproj.DotSettings, src/Asv.Drones.Gui.Core/Shell/Pages/Map/Planing/PlaningWidgetBase.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Map/Widgets/AnchorsEditorView.axaml, src/Asv.Drones.Gui.Core/Shell/Pages/Map/Widgets/AnchorsEditorView.axaml.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Map/Widgets/AnchorsEditorViewModel.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Map/Widgets/AnchorsEditorWidgetProvider.cs
AnchorsEditor has been added to the map widgets. This editor allows users to edit geo-location, represented by latitude, longitude, and altitude, of selected map items. This change enhances the user experience by providing an intuitive UI to alter the geo-location of map items which is useful in various use-cases like drone navigation, geo-plotting etc. Changes were also done to update related files which invoke the AnchorsEditor.
Asana: https://app.asana.com/0/1203851531040615/1205173127546645/f
=> feat: add AnchorsEditor in map widgets

src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/MissionStatus/MissionStatusViewModel.cs
The download implementation in MissionStatusViewModel now includes a try/catch block. This change aims to catch any exceptions that might occur during the mission download process. Previously, if the mission download failed for any reason, the error would not be caught, potentially causing a complete system crash. Now, such exceptions are caught and logged, preventing the system crash and providing a log message to aid in troubleshooting.
Asana: https://app.asana.com/0/1203851531040615/1205237266324943/f
=> fix(uav): add error handling to mission download

src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Dialogs/RecordStartView.axaml, src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Dialogs/RecordStartViewModel.cs
In this commit, I've enforced the width of the RecordStartView dialog to be 450 units. The Minimum and Maximum widths were also set to 450 units to ensure the dialog's size remains consistent across different user interactions. In addition, the button function in RecordStartViewModel was updated to only trigger if the information provided is valid. This is essential for preventing the application from accepting incorrect inputs, enhancing overall user experience and application's stability.
Asana: https://app.asana.com/0/1203851531040615/1205217582291092/f
=> fix(sdr): set fixed width for RecordStartView dialog

src/Asv.Drones.Gui.Map/MapView.axaml.cs
Removed 55ms delay in OnPointerMoved, because it could mess up anchor selection if it was done fast. Set core.MouseDown coords to 0 when pointer is released and add a check for core.MouseDown.IsEmpty before dragging the map.
Asana: https://app.asana.com/0/1203851531040615/1205290835733178/f
=> fix (map): fix map glitch and anchor selection

src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/FlightSdrView.axaml, src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/FlightSdrViewModel.cs
The previous implementation of the UI for selecting channels in the SDR flight view was cluttered and ambiguous. This change replaces the ToggleButton with a DropDownButton, which is a more intuitive UI component. Now, when the user clicks the DropDownButton (represented by the Table icon), a list of available channels will appear, from which the user can select and the channel's respective frequency will be displayed in the TextBox. This implementation is more efficient and user-friendly. The 'IsChannelInput' reactive property was removed as it's no longer needed with the new UI design.
Asana: https://app.asana.com/0/1203851531040615/1205307075789323/f
=> fix(sdr): refactor UI elements in the SDR flight view

src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Altitude.cs
The decimal format specifier in our Altitude service was updated from "F0" to "F2", to include 2 decimal places. This minor change for both Meters and Feet drastically improves the precision of altitude calculations and readouts in our GUI.
Asana: https://app.asana.com/0/1203851531040615/1205361528081959/f
=> fix (core): update altitude formatting to 2 decimal places

src/Asv.Drones.Gui.Uav/RS.Designer.cs, src/Asv.Drones.Gui.Uav/RS.resx, src/Asv.Drones.Gui.Uav/RS.ru.resx, src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/MissionStatus/MissionStatusView.axaml, src/Asv.Drones.Gui.Uav/Shell/Pages/Flight/Widgets/Uav/MissionStatus/MissionStatusViewModel.cs
This commit addresses changes in the mission status view regarding total & mission distances. Previously, the mission status view only displayed the total distance of all waypoints. Now, however, it is indeed enhanced to show the distance of the current mission, which is more relevant data to the user. Also, total distance now accounts for the distance from and to the home point.
This change aims to provide a clearer overview of distance-related metrics, thus assisting the user in staying aware of the drone's status and progress throughout the mission.
These modifications are reflected not only on the display elements and tooltips but also on the underlying ViewModel, where the calculation of the total distance has been adjusted to consider the home point distance. Besides, it includes …
=> fix: update mission status view with total and mission distances

src/Asv.Drones.Gui.Core/Shell/Pages/Map/Actions/AnchorMover/AnchorMoverActionView.axaml.cs
Hotkey for the editAnchorsToggleButton in AnchorMoverActionView was changed from LeftCtrl to LeftAlt. This change provides a more intuitive and less conflicting key configuration for users.
Asana: https://app.asana.com/0/1203851531040615/1205527219350697/f
=> feat: change hotkey for editAnchorsToggleButton

src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/FlightSdrViewModel.cs
This commit updates how the `RecordName` property is being assigned in the `FlightSdrViewModel` class. If there is a `SelectedMode`, it will append the current timestamp and the mode to form a unique recording name. The update aims at improving recording tracking and management by having more descriptive and informative recording names
Asana: https://app.asana.com/0/1203851531040615/1205628819726104/f
=> feat (sdr): update record name with timestamp and selected mode

src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Latitude.cs, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Longitude.cs
Changes have been made to reduce the precision of the printed coordinates from 7 decimal places to 6 in the "Latitude.cs" and "Longitude.cs" classes. This decision was made to streamline data presentation by limiting unnecessary precision, improving readability without significantly impacting accuracy.
Asana: https://app.asana.com/0/1203851531040615/1205678012462557/f
=> fix (loc): reduce precision in printing coordinates

src/Asv.Drones.Gui.Core/Controls/HierarchicalStore/HierarchicalStoreView.axaml, src/Asv.Drones.Gui.Core/Controls/HierarchicalStore/HierarchicalStoreViewModel.cs
Modified HierarchicalStore View layout to improve readability and introduced creation time display for files/folders in HierarchicalStore ViewModel. In the view, the adjustment prevents the last child of the Dockpanel from filling the whole available space for better UI. Description text is now docked to the right for clarity. Additionally, the ViewModel now includes the creation time display for files/folders when type details are fetched for FileSystemHierarchicalStoreEntry items. This provides more detailed information for the user.
Asana: https://app.asana.com/0/1203851531040615/1205628819726102/f
=> feat(core): update HierarchicalStore View and ViewModel

src/Asv.Drones.Gui.Sdr/Control/SdrPayloadBrowserViewModel.cs, src/Asv.Drones.Gui.Sdr/Control/SdrPayloadRecordViewModel.cs
A reference to IAsvSdrClientEx was added to SdrPayloadRecordViewModel to enable record deletion. The 'Delete' command is now created from a task invoking 'DeleteRecord' on _sdrClient. Consequently, SdrPayloadBrowserViewModel was also updated to pass IAsvSdrClientEx while transforming records.
Asana: https://app.asana.com/0/1203851531040615/1203719678217452/f
=> feat: add delete functionality to SdrPayloadRecordViewModel

src/Asv.Drones.Gui.Core/Controls/HierarchicalStore/HierarchicalStoreViewModel.cs, src/Asv.Drones.Gui.Custom.props, src/Asv.Drones.Gui.Sdr/Control/SdrStoreBrowserViewModel.cs
This commit updates the AsvMavlinkVersion to 3.4.2-alpha11 in Asv.Drones.Gui.Custom.props. Moreover, additional functionality has been added to the RefreshImpl () method of SdrStoreBrowserViewModel.cs to provide an UpdateEntries() condition for fileStore. It ensures updated records are fetched from the store during the refresh process. Also, a minor edit has been made to HierarchicalStoreViewModel.cs to maintain code cleanliness.
Asana: https://app.asana.com/0/1203851531040615/1205758515944602/f
=> fix: update AsvMavlinkVersion and enhance RefreshImpl function

src/Asv.Drones.Gui.Core/Controls/MaterialIconConverter.cs, src/Asv.Drones.Gui.Core/RS.Designer.cs, src/Asv.Drones.Gui.Core/RS.resx, src/Asv.Drones.Gui.Core/RS.ru.resx, src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/HeaderMenuItem.cs, src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/IHeaderMenuItem.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Map/Flight/FlightPageViewModel.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Map/HeaderAnchorsMenu.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageViewModel.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Map/Planing/PlaningPageViewModel.cs
This commit introduces a major change to the map page. A URI string is defined and a new constructor is added to the MapPageViewModel to take in a collection of IHeaderMenuItem. A transformation is added to the 'Markers' collection. This allows each IHeaderMenuItem to have its command linked to a map location, essentially adding support for an 'anchor' menu. An instance of 'HeaderAnchorsMenu' is sourced from the collection. If found, its items are set to the transformed collection.
A similar modification is made to PlaningPageViewModel, FlightPageViewModel - an exportedMenuItems parameter is added and passed on to super constructor. This ensures anchor menu support is uniform across these classes.
A new class HeaderAnchorsMenu is introduced. It exports itself as IHeaderMenuItem and has an …
=> feat: add anchor-menu support to map page

src/Asv.Drones.Gui.Sdr/Asv.Drones.Gui.Sdr.csproj.DotSettings, src/Asv.Drones.Gui.Sdr/RS.Designer.cs, src/Asv.Drones.Gui.Sdr/RS.resx, src/Asv.Drones.Gui.Sdr/RS.ru.resx, src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/FlightSdrViewModel.cs, src/Asv.Drones.Gui.Sdr/Shell/Pages/Settings/Sdr/SdrSettingsView.axaml, src/Asv.Drones.Gui.Sdr/Shell/Pages/Settings/Sdr/SdrSettingsView.axaml.cs, src/Asv.Drones.Gui.Sdr/Shell/Pages/Settings/Sdr/SdrSettingsViewModel.cs
Created a new settings section for Software-Defined Radio (SDR) configurations. This update includes the introduction of configurable default frequencies and channels for SDR components. Frequency configurations are provided for VOR, LLZ, and GP, each with the option to set a default channel. Adjustable file write frequency and data thinning settings have also been introduced. This enhancement allows users to set and alter SDR parameters according to their preference and specific requirements.
Asana: https://app.asana.com/0/1203851531040615/1203719678217439/f
=> feat: added SDR configurations in settings page.

src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageViewModel.cs
Updated the behavior of `MapPageViewModel` after a dialog closes. Now `SelectedItem` is reset to null, ensuring the previously selected item is not retained erroneously. This change should prevent potential inconsistencies in item selection and improve user interactions.
Asana: https://app.asana.com/0/1203851531040615/1205646452870160/f
=> fix: update behavior after dialog closes

src/Asv.Drones.Gui.Core/RS.Designer.cs, src/Asv.Drones.Gui.Core/RS.resx, src/Asv.Drones.Gui.Core/RS.ru.resx, src/Asv.Drones.Gui.Core/Services/Localization/MeasureUnits/Bearing.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Settings/MeasureUnits/MeasureUnitsSettingsView.axaml, src/Asv.Drones.Gui.Core/Shell/Pages/Settings/MeasureUnits/MeasureUnitsSettingsViewModel.cs, src/Asv.Drones.Gui.Core/Shell/ShellViewModel.cs, src/Asv.Drones.Gui.Custom.props
Added Degrees and Minutes unit option for drone bearing measurement and associated GUI controls. This change allows users to view and select either Degree or Degrees and Minutes for drone bearing. The GUI changes include the addition of a ComboBox for the selection of bearing unit and update in localization strings to reflect this new option. Also, updated AsvCommonVersion to 1.12.7.
Asana: https://app.asana.com/0/1203851531040615/1205412828145367/f
=> feat: added unit option for drone bearing measurement

src/Asv.Drones.Gui.Uav/RS.Designer.cs, src/Asv.Drones.Gui.Uav/RS.resx, src/Asv.Drones.Gui.Uav/RS.ru.resx, src/Asv.Drones.Gui.Uav/Shell/Pages/Parameters/ParamPageViewModel.cs
Localization for the dialog that warns users about potential data loss on the parameters page has been added. The content and button texts of the dialog have been moved to resource files, allowing for easier translation and adjustment of the dialog's language. The changes occurred in the RS.Designer.cs, RS.resx, ParamPageViewModel.cs, and RS.ru.resx files.
Asana: https://app.asana.com/0/1203851531040615/1205835806423473/f
=> feat (uav): add localization for data loss dialog in parameters page

src/Asv.Drones.Gui.Uav/Shell/Pages/Parameters/ParamPageView.axaml, src/Asv.Drones.Gui.Uav/Shell/Pages/Parameters/ParamPageViewModel.cs
Updated ParamPageViewModel.cs and ParamPageView.axaml to show a new icon indicating the sync status of a parameter.
This will enhance UX by allowing users to see at a glance whether their drones are in sync or not.
Asana: https://app.asana.com/0/1203851531040615/1205835806423480/f
=> feat (uav): add Sync status indicator to Params Page

src/Asv.Drones.Gui.Sdr/Control/SdrPayloadBrowserView.axaml, src/Asv.Drones.Gui.Sdr/Control/TagViewModel.cs
Changed how data is represented in the SdrPayloadBrowserView by updating the data binding in several TextBlock elements from "{Binding Name}" to "{Binding .}", which now references the current object in the data context. This adjustment was implemented to display the more descriptive output generated by the overriden ToString() methods that were added to various model classes in TagViewModel.cs. The ToString() methods now generate a string representing the name and value of each tag, providing additional clarity in the GUI.
Asana: https://app.asana.com/0/1203851531040615/1205906192538453/f
=> fix (sdr): update data binding in SdrPayloadBrowserView.axaml

src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/Items/Templater/Dialog/TemplaterView.axaml, src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/Items/Templater/Dialog/TemplaterViewModel.cs, src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/Items/Templater/DocxTemplate.cs, src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/Items/Templater/DocxTemplateHelper.cs, src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/Items/Templater/IDocxTemplate.cs, src/Asv.Drones.Gui.Core/Shell/Header/TopMenu/Tools/ToolsMenuItem.cs
Fixed a problem with the manual addition of image sizes in templates. The system now automatically calculates the sizes of the images injected into the `.docx` templates using the SkiaSharp library, rather than requiring manual input. This removes the possibility of errors due to incorrect dimensions. Also refactored Commands for adding tags in TemplaterViewModel for better clarity and performance. Minor GUI adjustments have been made for intuitive use. Finally, unnecessary white space and unused namespaces have been cleaned up.
Asana: https://app.asana.com/0/1203851531040615/1205412828145323/f
=> fix: update image processing and dimensions in templates

src/Asv.Drones.Gui.Sdr/Control/SdrPayloadBrowserViewModel.cs
Changes have been implemented in the SdrPayloadBrowserViewModel.cs to incorporate both ascending and descending sorting directions. This was spurred by the need to make sorting more dynamic, based on the value of IsSortByName. Additionally, an update has been introduced to trigger a download of records whenever a change is made to the 'IsSortByName' attribute.
Asana: https://app.asana.com/0/1203851531040615/1206007847454212/f
=> fix: update sorting logic in SdrPayloadBrowserViewModel

src/Asv.Drones.Gui.Core/Shell/Pages/Map/Widgets/AnchorsEditorView.axaml
This commit has restructured the AnchorsEditorView.axaml code for better readability and maintenance. Extra whitespaces and newline characters were removed. The changes also involve reordering of class instantiation, placing 'IsReadOnly' property before 'Interaction.Behaviors' for 'Longitude', 'Latitude' and 'Altitude' TextBox controls for uniformity. This should make the code more streamlined and easier to navigate.
Asana: https://app.asana.com/0/1203851531040615/1206045364656057/f
=> fix: refactored AnchorsEditorView.axaml for code cleanliness

src/Asv.Drones.Gui.Core/Controls/HierarchicalStore/HierarchicalStoreEntryTagViewModel.cs, src/Asv.Drones.Gui.Core/Controls/HierarchicalStore/HierarchicalStoreView.axaml
Removed auto-calculated Width property from HierarchicalStoreEntryTagViewModel, which was contributing to unnecessary complexity. Instead, width in UI components is managed purely on the UI side. Also removed related Width bind in the HierarchicalStoreView.axaml, making design cleaner and more consistent.
Asana: https://app.asana.com/0/1203851531040615/1206076614321403/f
=> fix: simplify HierarchicalStoreEntryTagViewModel implementation

src/Asv.Drones.Gui.Core/Asv.Drones.Gui.Core.csproj, src/Asv.Drones.Gui.Core/Shell/Pages/Map/Actions/Ruler/MapRulerActionViewModel.cs, src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageViewModel.cs
Changed ShowTargedDialog and SetUpRuler methods. The roulette button on the map is now disabled by pressing it a second time.
Asana: https://app.asana.com/0/1203851531040615/1204967469316979/f
=> Fixed ruler cancel 

src/Asv.Drones.Gui.Sdr/Shell/Pages/Flight/Widgets/Sdr/Rtt/CustomControls/VorSdrRttViewModel.cs
The conversion for Am30HzStringValue and Am9960HzStringValue was previously multiplied by 100 unnecessarily. This caused the calculated amplitude modulation values to be incorrect. Ensure these values now reflect the actual payload amplitude by removing the unwanted multiplication.
Asana: https://app.asana.com/0/1203851531040615/1206178229986185/f
=> hotfix (sdr): fixed incorrect amplitude conversion in VorSdrRttViewModel

src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageView.axaml, src/Asv.Drones.Gui.Core/Shell/Pages/Map/MapPageViewModel.cs
Add LostFocus behaviour for MapPageView.axaml, that invokes DeselectAnchorsCommand on it's viewmodel. This command disables SelectedItem on it's vm and checks for any selected anchors in Markers collection and sets IsSelected to false if there are any.
Asana: https://app.asana.com/0/1203851531040615/1206462230113635/f
=> fix (core): add deselect behaviour for map anchors

README.md
Enhance the documentation by adding detailed instructions for building and launching the Android application, ensuring clear guidance for developers. Simultaneously, correct and improve the description of the workload recovery process to provide more accurate and helpful information for maintaining operational continuity. These updates aim to facilitate a smoother development and recovery experience.
=> fix: update Android build/run instructions, revise workload recovery

src/Asv.Drones.Gui.Core/CorePlugin.cs, src/Asv.Drones.Gui/App.axaml.cs
Redundant creation of MainWindow object in App.xaml.cs is fixed for code optimization needs. Also found a bug with config save delay in CorePlugin. The delay was removed to immediately config refresh
=> fix(asv-drones): fix redundant object of type MainWindow creation and remove config delay

.github/workflows/ApiReleaseDeployAction.yml, src/Asv.Drones.Gui.Api/CompatibilitySuppressions.xml
Asana: https://app.asana.com/0/1203851531040615/1207381092055957/f
=> feat (asv-drones): add workflow for api to publish packet on GitHub

src/Asv.Drones.Gui/Shell/Pages/Flight/Widgets/Uav/FlightUavView.axaml, src/Asv.Drones.Gui/Shell/Pages/Flight/Widgets/Uav/MissionStatus/MissionStatusView.axaml
fix(uav): refactor MissionStatusView layout
- Reorganized the `MissionStatusView` layout to use `UniformGrid` for buttons.
- Moved mission status controls to `DockPanel.Bottom` within `FlightUavView`.
asana: https://app.asana.com/0/1203851531040615/1207643986818660/f
https://app.asana.com/0/1203851531040615/1207654116236034/f
=> fix(uav): refactor MissionStatusView layout

src/Asv.Drones.Gui.Api/RS.Designer.cs, src/Asv.Drones.Gui.Api/RS.resx, src/Asv.Drones.Gui.Api/RS.ru.resx, src/Asv.Drones.Gui.Api/Tools/Controls/Map/Widgets/AnchorEditor/AnchorsEditorView.axaml, src/Asv.Drones.Gui.Api/Tools/Controls/Map/Widgets/AnchorEditor/AnchorsEditorViewModel.cs, src/Asv.Drones.Gui/RS.Designer.cs, src/Asv.Drones.Gui/RS.resx, src/Asv.Drones.Gui/RS.ru.resx
In this PR: 
fix ArgumentNullException with null check of actions collection of anchor;
size optimization with more short locales; 
more efficient markup that allows the control to be used in a compressed state
Asana:
https://app.asana.com/0/1203851531040615/1207664866852418/f
https://app.asana.com/0/1203851531040615/1207654116236041/f
https://app.asana.com/0/1203851531040615/1207643849991138/f
=> Fix size optimization and ArgumentNullException in AnchorEditor widget

src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Installed/PluginsInstalledViewModel.cs, src/Asv.Drones.Gui/Shell/Pages/Settings/Plugins/Market/PluginsMarketViewModel.cs
Updated the SearchImpl method in PluginsMarket to retain the previously selected plugin after a search update, by comparing plugin IDs. Also applied code style improvements for readability and robustness.
The Clear call on _pluginSearchSource in PluginsInstalled was unnecessary given that AddOrUpdate effectively manages the items.
---
- https://app.asana.com/0/0/1208151005396126
=> fix (market): refactor plugin selection logic in SearchImpl method
